if not exists(select top 1 1 from [Seguridad].[tblUsuarios])
begin
	INSERT INTO Seguridad.tblUsuarios (Nombre, SegundoNombre, ApellidoPaterno, ApellidoMaterno, Email, [Password], Activo)
	VALUES 
		('John',		'Michael',		'Smith',		'Brown',	'john.smith@example.com',			CAST(NEWID() AS VARCHAR(500)), 1),
		('Mary',		'Elizabeth',	'Johnson',		'Miller',	'mary.johnson@example.com',			CAST(NEWID() AS VARCHAR(500)), 1),
		('James',		'Robert',		'Williams',		'Taylor',	'james.williams@example.com',		CAST(NEWID() AS VARCHAR(500)), 1),
		('Patricia',	'Linda',		'Jones',		'Wilson',	'patricia.jones@example.com',		CAST(NEWID() AS VARCHAR(500)), 1),
		('Michael',		'David',		'Brown',		'Anderson', 'michael.brown@example.com',		CAST(NEWID() AS VARCHAR(500)), 1),
		('Jennifer',	'Barbara',		'Garcia',		'Thomas',	'jennifer.garcia@example.com',		CAST(NEWID() AS VARCHAR(500)), 1),
		('William',		NULL,			'Martinez',		'Lee',		'william.martinez@example.com',		CAST(NEWID() AS VARCHAR(500)), 1),
		('Linda',		NULL,			'Clark',		'Scott',	'linda.clark@example.com',			CAST(NEWID() AS VARCHAR(500)), 1),
		('Richard',		NULL,			'Rodriguez',	'Green',	'richard.rodriguez@example.com',	CAST(NEWID() AS VARCHAR(500)), 1),
		('Karen',		NULL,			'Lewis',		'Walker',	'karen.lewis@example.com',			CAST(NEWID() AS VARCHAR(500)), 1),
		('Charles',		NULL,			'Lee',			'Hall',		'charles.lee@example.com',			CAST(NEWID() AS VARCHAR(500)), 1),
		('Jessica',		NULL,			'Gonzalez',		'Young',	'jessica.gonzalez@example.com',		CAST(NEWID() AS VARCHAR(500)), 1),
		('Daniel',		NULL,			'Hernandez',	'King',		'daniel.hernandez@example.com',		CAST(NEWID() AS VARCHAR(500)), 1),
		('Sarah',		NULL,			'Nelson',		'Wright',	'sarah.nelson@example.com',			CAST(NEWID() AS VARCHAR(500)), 1),
		('Mark',		NULL,			'Wright',		'Lopez',	'mark.wright@example.com',			CAST(NEWID() AS VARCHAR(500)), 1),
		('Betty',		NULL,			'Hill',			'Harris',	'betty.hill@example.com',			CAST(NEWID() AS VARCHAR(500)), 1),
		('Joseph',		NULL,			'King',			'Baker',	'joseph.king@example.com',			CAST(NEWID() AS VARCHAR(500)), 1),
		('Nancy',		NULL,			'Taylor',		'Adams',	'nancy.taylor@example.com',			CAST(NEWID() AS VARCHAR(500)), 1),
		('Susan',		NULL,			'White',		'Allen',	'susan.white@example.com',			CAST(NEWID() AS VARCHAR(500)), 1),
		('Matthew',		NULL,			'Thomas',		'Hall',		'matthew.thomas@example.com',		CAST(NEWID() AS VARCHAR(500)), 1),
		('Laura',		NULL,			'Thompson',		'Perez',	'laura.thompson@example.com',		CAST(NEWID() AS VARCHAR(500)), 1),
		('David',		NULL,			'Lopez',		'Young',	'david.lopez@example.com',			CAST(NEWID() AS VARCHAR(500)), 1),
		('Megan',		NULL,			'Harris',		'Mitchell', 'megan.harris@example.com',			CAST(NEWID() AS VARCHAR(500)), 1),
		('Kevin',		NULL,			'King',			'Wright',	'kevin.king@example.com',			CAST(NEWID() AS VARCHAR(500)), 1),
		('Michelle',	NULL,			'Clark',		'Garcia',	'michelle.clark@example.com',		CAST(NEWID() AS VARCHAR(500)), 1),
		('Jacob',		NULL,			'Lee',			'Thomas',	'jacob.lee@example.com',			CAST(NEWID() AS VARCHAR(500)), 1),
		('Amanda',		NULL,			'Jackson',		'Roberts',	'amanda.jackson@example.com',		CAST(NEWID() AS VARCHAR(500)), 1),
		('Justin',		NULL,			'Hernandez',	'Harris',	'justin.hernandez@example.com',		CAST(NEWID() AS VARCHAR(500)), 1),
		('Emily',		NULL,			'Young',		'Walker',	'emily.young@example.com',			CAST(NEWID() AS VARCHAR(500)), 1),
		('Brandon',		NULL,			'Gonzalez',		'Johnson',	'brandon.gonzalez@example.com',		CAST(NEWID() AS VARCHAR(500)), 1),
		('Samantha',	NULL,			'Lopez',		'Young',	'samantha.lopez@example.com',		CAST(NEWID() AS VARCHAR(500)), 1),
		('Benjamin',	NULL,			'Taylor',		'Gonzalez', 'benjamin.taylor@example.com',		CAST(NEWID() AS VARCHAR(500)), 1),
		('Nicole',		NULL,			'Wilson',		'Martin',	'nicole.wilson@example.com',		CAST(NEWID() AS VARCHAR(500)), 1),
		('Jeremy',		NULL,			'Anderson',		'Davis',	'jeremy.anderson@example.com',		CAST(NEWID() AS VARCHAR(500)), 1),
		('Rachel',		NULL,			'Thomas',		'Robinson', 'rachel.thomas@example.com',		CAST(NEWID() AS VARCHAR(500)), 1),
		('Alexander',	NULL,			'Martinez',		'Allen',	'alexander.martinez@example.com',	CAST(NEWID() AS VARCHAR(500)), 1),
		('Heather',		NULL,			'Young',		'Garcia',	'heather.young@example.com',		CAST(NEWID() AS VARCHAR(500)), 1),
		('Andrew',		NULL,			'Scott',		'Lopez',	'andrew.scott@example.com',			CAST(NEWID() AS VARCHAR(500)), 1)
	;
END